### ISSUE TITLE
Directory.Delete(outPath, true)

### ISSUE THREAD

**Issue by namidaka** [SamboyCoding/Fmod5Sharp#10]
Seriously? What kind of Psychopath does that , without even asking for confirmation.
My bad for executing code without reading it completely first i guess.

**Comment by SamboyCoding** [comment]
The bank extractor is literally just used for development and debugging purposes. I didn't intend for, nor expect, anyone to download the project, compile it without reading the (very small) file, and then run it on a directory containing important stuff. This is why there is no published release, nor mention of the bank extractor in the readme. This point of this repository is the library.
