### ISSUE TITLE
Vorbis Decoder occasionally produces invalid files

### ISSUE THREAD

**Issue by SamboyCoding** [SamboyCoding/Fmod5Sharp#2]
Ref [ds5678/AssetRipper/#179](https://github.com/ds5678/AssetRipper/issues/179).

That issue contains a vorbis-encoded FSB file which results in an invalid OGG being produced, and another which occasionally produces an invalid OGG when running multi-threaded. 

If we switch to a combination of https://github.com/SteveLillis/.NET-Ogg-Vorbis-Encoder/ for writing, and roll our own parser for the setup blobs, it should be possible to remove the dependency on OggVorbisSharp (and thus the native libs, and .NET 6.0).

**Comment by lab313ru** [comment]
Fixed implementation that doesn't require libogg and libvorbis anymore: https://gist.github.com/lab313ru/54a9b77d10e8b81c9cef2ac6340563f7

**Comment by ds5678** [comment]
@lab313ru I'm working on a PR based on your gist, and I have a couple questions:
1. Are you licensing your gist under MIT?
2. In [vorbis_headers.json](https://gist.github.com/lab313ru/54a9b77d10e8b81c9cef2ac6340563f7#file-vorbis_headers-json), you have lists of 6 integers each. 
    * Where did those come from? 
    * Why is only the last integer used in code?
    * Why are they important?

**Comment by SamboyCoding** [comment]
This has been addressed in d9aec6fb7e5a07ae1109d50c4c92825064be5c8d. Sorry for the wait!
