### ISSUE TITLE
I found a case when it seems that the standard format does not decode

### ISSUE THREAD

**Issue by pavlo-kravchenko** [SamboyCoding/Fmod5Sharp#7]
This is one of the banks of the Darkest Dungeon game.
It's called music.bank.
You can write to me and I will reset the file itself.

**Comment by SamboyCoding** [comment]
I'd need a lot more info than this to start, for example any error you get, what internal format the bank is identified as, etc

**Comment by pavlo-kravchenko** [comment]
I get just "Failed to extract sample"
MyBank!.Header.AudioType = 16 (from method RebuildAsStandardFileFormat)
What other information can I provide?

**Comment by SamboyCoding** [comment]
16 is a new file format, FADPCM. I would need the bank file to work investigate further.

**Comment by pavlo-kravchenko** [comment]
Where can I send it?

**Comment by SamboyCoding** [comment]
If you have discord you can communicate with me in the server I have for my projects https://discord.gg/XdggT7XZXm

**Comment by Devyatyi9** [comment]
@SamboyCoding Is there any news on FADPCM format? I know that fsbank.exe from FMOD Studio API can generate files with this format. Also fsb_aud_extr_1_10.exe (not from API) can read and decompress this format from fsb and convert to wav. There is also [plugin for foobar2000](https://www.foobar2000.org/components/view/foo_input_vgmstream) for playing different game formats, where there is support for Fmod bank and Fmod FSB5 FADPCM.
"FMOD Studio API Windows\bin\x64\fsbank.exe"
 ![image](https://github.com/SamboyCoding/Fmod5Sharp/assets/5161472/c25b954c-2b0c-4808-b0aa-37edf0b46685).
https://www.fmod.com/download#fmodengine

**Comment by SamboyCoding** [comment]
Partial FADPCM support implemented in https://github.com/SamboyCoding/Fmod5Sharp/commit/9d932648712aef225b638f735c0f9f893faae76c but it's not working properly yet

**Comment by ds5678** [comment]
I have a project that might help with implementing support for additional formats.

https://github.com/AssetRipper/WavToFsb

Though this line will need to be changed:

https://github.com/AssetRipper/WavToFsb/blob/cb5e4139a600573c8579bf7c826d64811a8f3eb0/WavToFsb/Program.cs#L35

**Comment by SamboyCoding** [comment]
The issue doesn't so much lie in having access to the files as much as it does demand. As detailed in the readme, most of the remaining unimplemented format simply do not get used often enough for it to be worth implementing them.
